---
# tasks file for windows-workstation

### Req dot net 4.5.2 
#- name: Install .Net framework 4.5.2 
#  win_feature:
#    name: DotNet-4-5-2
#    state: present
#    Win2016 has .NET 4.6... 
- block:
  - set_fact:
      user: "{{ user_prefix }}{{ inventory_hostname | regex_replace('[^0-9]', '') }}"

  - name: Install Visual Studio Code, Git, and Putty
    win_chocolatey:
      name: "{{ item }}"
    with_items:
      - visualstudiocode
      - git
      - putty.install
      - firefox
      - googlechrome
      - winscp
      #- atom
      #- notepadplusplus.install
      #- sublimetext3

  - name: Add Putty Shortcut to administrator desktop
    win_shortcut:
      description: PuTTY
      src: '%ProgramFiles%\PuTTY\putty.exe'
      dest: '%Public%\Desktop\Putty.lnk'
      directory: '%ProgramFiles%\PuTTY\'

  - name: Allow insecure git repos for self signed certificates
    win_command: git config --global http.sslVerify "false"

  - name: Set git user 
    win_command: git config --global user.name "{{ user }}"

  - name: Set git user email
    win_command: git config --global user.email "{{ user }}@{{ dns_domain_name }}"

  - name: Set git to cache credentials
    win_command: git config --global credential.helper store

  - name: Set git password
    win_template:
      src: templates/git-credentials.j2
      dest: C:\Users\{{ user }}\.git-credentials

  - name: Set git to cache credentials
    win_command: git clone https://gitlab.ansibleworkshop.com/{{ user }}/{{ user }}.git
    args:
      chdir: C:\Users\{{ user }}\Documents
      creates: C:\Users\{{ user }}\Documents\{{ user }}

  - name: Set Chrome to default Browser
    win_shell: Set-ItemProperty HKCU:\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\{{ item }}\UserChoice -name ProgId ChromeHTML
    with_items:
      - ftp
      - http
      - https

  become: yes
  become_user: "ansibleworkshop\\{{ user_prefix }}{{ inventory_hostname | regex_replace('[^0-9]', '') }}"
  become_method: runas

#- include_tasks: ansible.yml
