---
# tasks file for windows-workstation

### Req dot net 4.5.2 
#- name: Install .Net framework 4.5.2 
#  win_feature:
#    name: DotNet-4-5-2
#    state: present
#    Win2016 has .NET 4.6... 

- name: Install Visual Studio Code, Git, and Putty
  win_chocolatey:
    name: "{{ item }}"
  with_items:
    - visualstudiocode
    - git
    - putty.install
    - firefox
    #- googlechrome
    - winscp
#    - cygwin
#    - cyg-get
    #- atom
    #- notepadplusplus.install
    #- sublimetext3

#- name: Install extra Cygwin Modules
#  win_command: cyg-get.bat curl cygwin32-gcc-g++ gcc-core gcc-g++ git libffi-devel make nano openssl openssl-devel python-crypto python2 python2-devel python2-openssl python2-pip python2-setuptools python-pywinrm tree
#  args:
#    chdir: C:\ProgramData\chocolatey\bin\

#- name: Install Ansible
#  win_command: bash.exe -l -c "pip2 install ansible"
#  args:
#    chdir: c:\tools\cygwin\bin\

#- name: Create Ansible Config directory
#  win_file:
#    path: C:\tools\cygwin\etc\ansible
#    state: directory

#- name: Copy Ansible Config file
#  win_copy:
#    src: files/ansible.cfg
#    dest: C:\tools\cygwin\etc\ansible\ansible.cfg

#- name: Copy sshpass.exe to workstation
#  win_copy:
#    src: files/sshpass.exe
#    dest: C:\tools\cygwin\bin\sshpass.exe

- name: Add Putty Shortcut to administrator desktop
  win_shortcut:
    description: PuTTY
    src: '%ProgramFiles%\PuTTY\putty.exe'
    dest: '%Public%\Desktop\Putty.lnk'
    directory: '%ProgramFiles%\PuTTY\'

- name: Allow insecure git repos for self signed certificates
  win_command: git config --global http.sslVerify "false"

- name: Set git user 
  win_command: git config --global user.name "{{ user_prefix }}{{ inventory_hostname | regex_replace('\\D') }}"

- name: Set git user email
  win_command: git config --global user.email "{{ user_prefix }}{{ inventory_hostname | regex_replace('\\D') }}@{{ dns_domain_name }}"

- name: Set git to cache credentials
  win_command: git config --global credential.helper wincred

