---

# ----------------------- Destroy Tower Instances -----------------------
- name: Destory Tower Instances
  vmware_guest2:
    hostname: "{{ vCenterServer }}"
    username: "{{ vCenterUsername }}"
    password: "{{ vCenterPassword }}"
    datacenter: "{{ vCenterDatacenter }}"
    cluster: "{{ vCenterCluster }}"
    folder: "{{ vCenterFolder }}"
    name: "{{ name_prefix }}-s{{ item }}-tower"
    validate_certs: false
    state: absent
    force: yes
  with_sequence: count={{ user_count }}

# ----------------------- Destroy Gitlab Instances -----------------------
- name: Destory Gitlab Instances
  vmware_guest2:
    hostname: "{{ vCenterServer }}"
    username: "{{ vCenterUsername }}"
    password: "{{ vCenterPassword }}"
    datacenter: "{{ vCenterDatacenter }}"
    cluster: "{{ vCenterCluster }}"
    folder: "{{ vCenterFolder }}"
    name: "{{ name_prefix }}-gitlab"
    validate_certs: false
    state: absent
    force: yes

# ----------------------- Destroy DC Instances -----------------------
- name: Destory DC Instances
  vmware_guest2:
    hostname: "{{ vCenterServer }}"
    username: "{{ vCenterUsername }}"
    password: "{{ vCenterPassword }}"
    datacenter: "{{ vCenterDatacenter }}"
    cluster: "{{ vCenterCluster }}"
    folder: "{{ vCenterFolder }}"
    name: "{{ name_prefix }}-dc"
    validate_certs: false
    state: absent
    force: yes

# ----------------------- Destroy Windows Instances -----------------------
- name: Destory Windows Instances
  vmware_guest2:
    hostname: "{{ vCenterServer }}"
    username: "{{ vCenterUsername }}"
    password: "{{ vCenterPassword }}"
    datacenter: "{{ vCenterDatacenter }}"
    cluster: "{{ vCenterCluster }}"
    folder: "{{ vCenterFolder }}"
    name: "{{ name_prefix }}-s{{ item }}-win1"
    validate_certs: false
    state: absent
    force: yes
  with_sequence: count={{ user_count }}

# ----------------------- Destroy Workstation Instances -----------------------
- name: Destory Workstation Instances
vmware_guest2:
    hostname: "{{ vCenterServer }}"
    username: "{{ vCenterUsername }}"
    password: "{{ vCenterPassword }}"
    datacenter: "{{ vCenterDatacenter }}"
    cluster: "{{ vCenterCluster }}"
    folder: "{{ vCenterFolder }}"
    name: "{{ name_prefix }}-s{{ item }}-work"
    validate_certs: false
    state: absent
    force: yes
  with_sequence: count={{ user_count }}
