---
- name: Sleep 3 minutes before attempting to install... sigh...
  pause:
    minutes: 3

- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: True
    include_sub_features: True
  register: winfeature

- name: Reboot if needed
  win_reboot:
  when: winfeature.changed

#- name: Sleep 180 seconds to wait for DNS config
#  pause:
#    minutes: 3
#  when: winfeature.changed

#- name: Install AD-Certificate
#  win_feature:
#    name: AD-Certificate
#    state: present
#    include_management_tools: True
#    include_sub_features: True
#  register: wincertfeature

#- debug: var=wincertfeature

#- name: Reboot if needed
#  win_reboot:
#  when: wincertfeature.reboot_required

- name: Install DNS
  win_feature:
    name: DNS
    state: present
    include_management_tools: True
  register: windnsfeature

- name: Reboot if needed
  win_reboot:
  when: windnsfeature.reboot_required

#- name: Sleep 180 seconds to wait for DNS config
#  pause:
#    minutes: 3
#  when: windnsfeature.changed
#
#- name: Ensure AD services are started - will fail if install not complete
#  win_service:
#    name: "{{ item }}"
#    state: started
#    start_mode: auto
#  with_items:
#    - adws
#    - dns
#    - kdc
#    - netlogon

# Validate?
# DCDIAG
# Get-Service adws,kdc,netlogon,dns     # Services are running?
# Get-smbshare          # sysvol & netlogin shares
# get-eventlog "Directory Service" | select entrytype, source, eventid, message

# get-eventlog "Active Directory Web Services" | select entrytype, source, eventid, message

- name: Create DNS Domain
  win_domain:
    dns_domain_name: "{{ dns_domain_name }}"
    safe_mode_password: "{{ domain_admin_password }}"
  register: windomain

- name: Reboot if needed
  win_reboot:
  when: windomain.reboot_required

# For some reason on a run after reboot I'm getting an error sometimes
# Error message was MODULE FAILURE:
# Exception calling \"Run\" with \"1\" argument(s): \"Exception calling \"Invoke\" with \"0\" argument(s): \"The running command \r\nstopped because the preference variable \"ErrorActionPreference\" or common parameter is set to Stop: The specified \r\nargument 'InstallDNS' was not recognized.
# I added this sleep to see if it helps
#- name: Sleep 3 minutes after reboot from DNS configuration
#  pause:
#    minutes: 3
#  when: windomain.reboot_required

#- name: Ensure DNS services are started
#  win_service:
#    name: "{{ item }}"
#    state: started
#    start_mode: auto
#  with_items:
#    - dns

#- name: Get current DNS zones
#  win_shell: Get-DnsServerZone | Select ZoneName
#  changed_when: false
#  register: dnsserverzone
#
#- debug: var=dnsserverzone
#
#- debug: var=ptr_zone_cidr
#
#- name: Set Reverse Lookup Zone
#  win_shell: Add-DnsServerPrimaryZone -NetworkId "{{ ptr_zone_cidr }}" -DynamicUpdate Secure -ReplicationScope Domain
#  when: "ptr_zone_name not in dnsserverzone.stdout"

#- name: Ensure AD services are started - will fail if install not complete
#  win_service:
#    name: "{{ item }}"
#    state: started
#    start_mode: auto
#  with_items:
#    - adws
#    - dns
#    - kdc
#    - netlogon

#
#- name: Promote to Domain Controller
#  win_domain_controller:
#    dns_domain_name: "{{ dns_domain_name }}"
#    domain_admin_user: "administrator@{{ dns_domain_name }}"
#    domain_admin_password: "{{ domain_admin_password }}"
#    safe_mode_password: "{{ domain_admin_password }}"
#    state: domain_controller
#    log_path: c:\ansible_win_domain_controller.txt
#  register: windc
#
#- name: Reboot if needed
#  win_reboot:
#  when: windc.reboot_required
#
#- name: Sleep 180 seconds before adding windows group... sigh...
#  pause:
#    minutes: 3
#  when: windc.changed
#
- name: Ensure AD services are started - will fail if install not complete
  win_service:
    name: "{{ item }}"
    state: started
    start_mode: auto
  with_items:
    - adws
    - dns
#    - kdc
#    - netlogon
#
#- name: Get current DNS zones
#  win_shell: Get-DnsServerZone | Select ZoneName
#  changed_when: false
#  register: dnsserverzone

#- debug: var=dnsserverzone

#- win_chocolatey:
#    name: psexec
#    state: present
#  register: psexec_install

#- win_reboot:
#  when: psexec_install.changed

#- win_psexec:
#    command: C:\ProgramData\chocolatey\choco.exe install powershell -y
#    system: yes

#- name:
#  win_psmodule:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - xNetworking
#    - xDnsServer

#- name: Set Reverse Lookup Zone - fails first time
#  win_shell: Add-DnsServerPrimaryZone -NetworkId "{{ ptr_zone_cidr }}" -DynamicUpdate Secure -ReplicationScope Domain
#  when: "ptr_zone_name not in dnsserverzone.stdout"
#  register: result
#  until: result|success
#  retries: 5
#  delay: 60

#- name: Create A record for gitlab
#  win_dsc:
#    resource_name: xDnsRecord
#    Name: gitlab
#    Zone: "{{ dns_domain_name }}"
#    Target: "{{ hostvars['gitlab']['ansible_host'] }}"
#    Type: ARecord


- name: Get A records for zone
  win_shell: Get-DnsServerResourceRecord -ZoneName {{ dns_domain_name }} -RRType A | Format-Table -AutoSize -Wrap
  changed_when: false
  register: arecords

#- debug: var=arecords

- name: Create A record for gitlab
  win_shell: Add-DnsServerResourceRecordA -Name "gitlab" -ZoneName "{{ dns_domain_name }}" -AllowUpdateAny -Ipv4Address "{{ hostvars['gitlab']['ansible_host'] }}" -TimeToLive 01:00:00 -AgeRecord
  when: "'gitlab' not in arecords.stdout"

- name: Create A record for docs
  win_shell: Add-DnsServerResourceRecordA -Name "docs" -ZoneName "{{ dns_domain_name }}" -AllowUpdateAny -Ipv4Address "{{ hostvars['docs']['ansible_host'] }}" -TimeToLive 01:00:00 -AgeRecord
  when: "'docs' not in arecords.stdout"

- name: Create A record for Towers
  win_shell: Add-DnsServerResourceRecordA -Name "s{{ item }}-tower" -ZoneName "{{ dns_domain_name }}" -AllowUpdateAny -Ipv4Address "{{ hostvars['s' + item + '-tower']['ansible_host'] }}" -TimeToLive 01:00:00 -AgeRecord
  when: "'s{{ item }}-tower' not in arecords.stdout"
  with_sequence: count={{ user_count }}

- name: Create A record for Windows
  win_shell: Add-DnsServerResourceRecordA -Name "s{{ item }}-win" -ZoneName "{{ dns_domain_name }}" -AllowUpdateAny -Ipv4Address "{{ hostvars['s' + item + '-win']['ansible_host'] }}" -TimeToLive 01:00:00 -AgeRecord
  when: "'s{{ item }}-win' not in arecords.stdout"
  with_sequence: count={{ user_count }}

#- name: Get PTR Records for zone
#  win_shell: Get-DnsServerResourceRecord -ZoneName {{ ptr_zone_name }} -RRType PTR | Format-Table -AutoSize -Wrap
#  register: ptr_records

#- debug: var=ptr_records
#
#- debug: msg="item = {{ item }}"
#  with_items: "{{ groups.all }}"

# Add-DnsServerResourceRecordPtr -Name "17" -ZoneName "1.168.192.in-addr.arpa" -AllowUpdateAny -TimeToLive 01:00:00 -AgeRecord -PtrDomainName "hostname.example.com"
#- name: Set PTR Record for each host
#  win_shell: Add-DnsServerResourceRecordPtr -Name "{{ hostvars[item]['ansible_host'].split('.')[3] }}" -ZoneName "{{ ptr_zone_name }}" -AllowUpdateAny -TimeToLive 01:00:00 -AgeRecord -PtrDomainName "{{ item + '.' + dns_domain_name}}"
#  when: "item not in ptr_records.stdout"
#  with_items: "{{groups.all}}"

- name: Sleep 60 seconds before adding windows group... sigh...
  pause:
    minutes: 1
  when: windomain.changed


- name: Add windows group
  win_domain_group:
    name: Ansible Users
    scope: global
    #path: OU=Users,DC=ansibleworkshop,DC=com

- name: Add windows domain admin
  win_domain_user:
    name: "Admin"
    upn: "Admin@{{ dns_domain_name }}"
    state: present
    enabled: yes
    account_locked: no
    groups:
      - Domain Admins
    password: "{{ domain_admin_password }}"
    update_password: on_create
    password_expired: false
    firstname: admin
    surname: user
    company: AnsibleByRedHat
    email: "Admin@{{ dns_domain_name }}"
    #path: ou=Users,dc=ansibleworkshop,dc=com


- name: Add windows AD users
  win_domain_user:
    name: "{{ user_prefix }}{{ item }}"
    upn: "{{ user_prefix}}{{ item }}@{{ dns_domain_name }}"
    state: present
    enabled: yes
    account_locked: no
    groups:
      - Ansible Users
    password: "{{ users_password }}"
    update_password: on_create
    password_expired: false
    firstname: "{{ user_prefix }}"
    surname: "{{ item }}"
    company: AnsibleByRedHat
    email: "{{user_prefix}}{{ item }}@{{ dns_domain_name }}"
  with_sequence: count="{{ user_count }}"

#- name: Get current DNS search string
#  win_shell: Get-DnsClientGlobalSetting | Select SuffixSearchList
#  changed_when: false
#  register: suffixsearchlist

#- debug: var=suffixsearchlist

#- name: Set DNS search string
#  win_shell: Set-DnsClientGlobalSetting -SuffixSearchList {{ dns_domain_name }}, ec2.internal
#  when: "dns_domain_name not in suffixsearchlist.stdout"

#- name: Set DNS search string
#  win_dsc:
#    resource_name: xDnsClientGlobalSetting
#    IsSingleInstance: 'Yes'
#    SuffixSearchList: ["{{ dns_domain_name }}", 'ec2.internal']

- name: Get current DNS search string
  win_shell: Get-DnsClientGlobalSetting | Select SuffixSearchList
  changed_when: false
  register: suffixsearchlist

- name: Set DNS search string
  win_shell: Set-DnsClientGlobalSetting -SuffixSearchList {{ dns_domain_name }}, ec2.internal
  when: "dns_domain_name not in suffixsearchlist.stdout"
